### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by zdog234** [arthurhenrique/cookiecutter-fastapi#8]
Hello, thanks for putting this together :)

Sorry if there's a license somewhere, but I wasn't able to find one.

Would you be up for adding a `LICENSE` file? For purely selfish reasons, I'd appreciate if it were permissive (e.g. Apache, MIT), but GPL would be better than nothing :)

Thanks again

**Comment by arthurhenrique** [comment]
Hello @zdog234, 
I have added an MIT license for this project, thank you for your issue. 
Is it ok?

**Comment by zdog234** [comment]
looks good to me! Thanks :)
